name: CI/CD MLflow

# Beri GITHUB_TOKEN izin menulis konten
permissions:
  contents: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code (dengan token untuk push)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Install dependencies
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn matplotlib

      # 4. Run MLflow Project untuk retrain
      - name: Run MLflow Project
        run: |
          mlflow run MLproject --env-manager=local \
            -P n_estimators=100 \
            -P max_depth=20

      # 5. Ambil run_id terakhir
      - name: Get latest MLflow run_id
        run: |
          echo "RUN_ID=$(ls -td mlruns/0/*/ | head -n1 | xargs basename)" >> $GITHUB_ENV

      # 6. Setup Git LFS & track artefak model
      - name: Install Git LFS
        run: |
          sudo apt-get update && sudo apt-get install git-lfs -y
          git lfs install
      - name: Track MLflow model artifacts
        run: |
          git lfs track "mlruns/0/$RUN_ID/artifacts/model/**"
          git add .gitattributes

      # 7. Commit & push artifacts ke GitHub
      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit MLflow artifacts
        run: |
          git add mlruns/0/$RUN_ID/artifacts/model/
          git diff --quiet && echo "No new artifacts to commit" || git commit -m "chore: add MLflow model artifacts for run $RUN_ID [skip ci]"
      - name: Push artifacts to GitHub
        run: git push origin master

      # 8. Build Docker image untuk serving
      - name: Build MLflow serving Docker image
        run: |
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "mh-model"

      # 9. Docker Hub login & push
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker image
        run: |
          docker tag mh-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/mh-model:latest
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mh-model:latest
