name: CI - MLflow Project

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn matplotlib

      - name: Run MLflow Project (no conda)
        run: |
          mlflow run ml_ci_project --env-manager=local \
            -P n_estimators=150 \
            -P max_depth=15

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: mh-model
          path: mlruns/0/*/artifacts/model/

  docker:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: MLProject/Dockerfile
          push: true
          tags: adrianramadhan/mh-ml-model:latest
