name: CI - MLflow Project

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLproject/conda.yaml
          activate-environment: mlproject-env

      - name: Install pip deps
        run: |
          pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn matplotlib

      - name: Run MLflow Project
        run: |
          mlflow run MLproject --env-manager=local \
            -P n_estimators=100 \
            -P max_depth=20

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: mh-model
          path: mlruns/0/*/artifacts/model/

  docker:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: MLproject/Dockerfile
          push: true
          tags: adrianramadhan/mh-ml-model:latest
